name: building
on: push

jobs:
  build:
    name: My Job Matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12, 14]      
    steps:
     - name: my step
       env: 
         MY_VAR: Hi there!
         FIRST_NAME: Newton
         MIDDLE_NAME: Costa
       run: ehco $MY_VAR $FIRST_NAME $MIDDLE_NAME
    
