name: building
on: push

jobs:
  build:
    name: My Job Matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12]      
    steps:
     - name: my step 1
       env: 
         MY_VAR: Hi there!
         FIRST_NAME: Newton
         MIDDLE_NAME: Costa
       run: echo $MY_VAR $FIRST_NAME $MIDDLE_NAME
     - name: my step 2
       if: success()
       run: echo " the previous step has finished successfully"
     - name: my step 3
       uses: actions/checkout@v1
       with:
        node-version: 12
        registry-url: https://npm.pkg.github.com/
    
