name: building
on: pull_request

jobs:
  build:
    name: My Job Matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12]      
    steps:
     - name: my step 1
       env: 
         MY_VAR: Hi there!
         FIRST_NAME: Newton
         MIDDLE_NAME: Costa
       run: echo $MY_VAR $FIRST_NAME $MIDDLE_NAME
     - name: my step 2
       if: success()
       run: echo " the previous step has finished successfully"
     - name: my step 3
       uses: actions/checkout@v1
       with:
        node-version: 12
        registry-url: https://npm.pkg.github.com/
     - name: my step 4
       uses: actions/first-interaction@v1
       with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Essage that will display on users first issue'
        pr-message: 'message that will be displayed on users first pr'
        
    
